### PR TITLE
Fixes more #1241

### PR DESCRIPTION
**Pull request by Pofigizm**
I haven't `ready` function when i use polymer-micro.html
I think, it's better to use `attached` function, because it is basic lifecycle callbacks.

### CODE REVIEW

**Comment by Pofigizm** [comment]
My CLA has been submitted.

**Comment by arthurevans** [comment]
@sorvell or @kevinpschaaf should probably review this one.

**Comment by Pofigizm** [comment]
In PRIMER.md:274 also wrong example. Need change to attached:

**Comment by Pofigizm** [comment]
I don't want include https://github.com/Pofigizm/polymer/commit/7d2398888f4d6049d59d82931cf678f8636d7317 to this PR. I don't understand why it came here.

**Pull request closed without merging**
