### PR TITLE
[1/2] Update authors

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@kevinpschaaf, @valdrinkoshi, @azakus, please merge this pull request.

**Comment by notwaldorf** [comment]
This change isn't needed, since we're already linking to the authors file in all of the license headers ([example](https://github.com/webcomponents/webcomponentsjs/blob/master/src/pre-polyfill.js#L5)). Also, FYI, we use the "Polymer" not "Polymer Project" name.

**Comment by FluorescentHallucinogen** [comment]
@notwaldorf
> Also, FYI, we use the "Polymer" not "Polymer Project" name.

But you use "Polymer Project": https://github.com/Polymer/polymer/blob/master/package.json#L41

Please correct it in `package.json` in this case.

Also I've used HTTPS URL instead of HTTP.

**Comment by FluorescentHallucinogen** [comment]
@notwaldorf

And you already use linking to the authors file in `bower.json`: https://github.com/Polymer/polymer/blob/master/bower.json#L17

Please correct it in `bower.json` in this case.

**Pull request closed without merging**
