### PR TITLE
Introduce new API for `debouncer` and `Async`

### PR DESCRIPTION
**Pull request by blasten**
This PR is aimed to provide fine-tuning for scheduling async work without breaking any of the legacy APIs.

### Why?

Polymer 1 includes a few utility methods for scheduling async work and debouncing functions. These methods come in the form of `Polymer.Base.debounce` and `Polymer.Base.Async`. They both allow to schedule work that runs in either the next micro task or when a timer fires if a wait time is provided. One great thing about this implementation is the ability to flush all the async work at any given time for testing, debugging, or managing async dependencies.

However, in many cases [1], [2], [3], async work needs to happen after browser layout or when the main threat is idle. Similarly, some debounce functions should run during these periods to ensure correctness and improve performance.

[1] Measuring DOM elements.
[2] Incremental rendering.
[3] Expensive work in general (no DOM related).

In Polymer, there are a few relevant cases:

* rAF: Layout needs to happen before doing work on the `connected` callback, the "resizeHandler"(responding to the iron-resize event) or some observer to a property.

* Incremental rendering in iron-list where the timing for the debouncer is changed depending on these factors:
  1. Rendering work on the `attached` callback goes after rAF.
  2. Similarly,` iron-resize` work is done after rAF.
  3. on-screen items is done within a micro task.
  4. off-screen items is done during idle periods.

### Changes for consideration

1. `Polymer.Async.run` -> `Polymer.Async.microTask.run` or `Polymer.Async.timeOut.run` Potentially avoidable by adding a `run` and cancel method to `Polymer.Async`

2. `Polymer.Debouncer.debounce(debouncer, callback, wait, context)` -> `Polymer.Debouncer.debounce(debouncer, asyncModule, callback)` Also potentially avoidable if checking `arguments.length`

Fixes https://github.com/Polymer/polymer/issues/3895

### CODE REVIEW

**Comment by azakus** [comment]
I'm a little confused by the chaining API you have proposed here. Would it ever make sense to make a debouncer and not call `after` or `run` on it?
If not, we could just make an API that looks more like the older API, but just take an object for the `wait` field that corresponds to what you have in `after`.

You could also drop `context` by requiring users write`() =>{}` notation or function binding for the callback.

Example:
```
Polymer.Debouncer.debounce(
  job: object, 
  callback: fn,
  asyncModule: {run: fn, cancel: fn},
  ...moduleArgs: passed to asyncModule.run
);
```

WDYT?

**Comment by blasten** [comment]
@azakus That is a fair point. I think the only reason for such change was "it's more readable". I originally intended to make `Polymer.Debouncer.debounce().after()` "thenable".

**Comment by blasten** [comment]
PTAL @azakus @sorvell

**Comment by azakus** [comment]
LGTM from @sorvell

**Comment by blasten** [comment]
yay 🎉 🙌

**Pull request merged**
