### PR TITLE
Use the new .github folder for issue and pull request templates

### PR DESCRIPTION
**Pull request by abdonrd**
### Description

Use the new `.github` folder for issue and pull request templates

Blog post reference: https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by abdonrd** [comment]
@azakus PTAL

**Comment by azakus** [comment]
HMM, I'll need @tjsavage to sign off on the CONTRIBUTING.md move, can you just move the template files?

**Comment by abdonrd** [comment]
@azakus sure!

**Comment by tjsavage** [comment]
LGTM, I'd rather keep CONTRIBUTING in the main repo, since it's not specific to Github.

**Comment by abdonrd** [comment]
@tjsavage I thought that the CONTRIBUTING.md is only used for GitHub Contributing Guidelines:

screen shot 2016-02-17 at 23 17 36

@azakus PR updated!

**Comment by ebidel** [comment]
It's common in OS to have a top-level CONTRIBUTING. We should probably keep it put. We're also linking to it in a bunch of places. Moving it would break those links :\

**Comment by abdonrd** [comment]
@ebidel thanks for the explication!

**Comment by azakus** [comment]
LGTM, thanks!

**Pull request merged**
