### PR TITLE
Fix compiling with Polymer({}) calls

### PR DESCRIPTION
**Pull request by azakus**
Add types for instance properties of ElementMixin and LegacyElementMixin

### CODE REVIEW

**Comment by TimvdLippe** [comment]
How can I test that this solves the closure warnings?

**Comment by azakus** [comment]
@TimvdLippe with https://github.com/polymerlabs/polymer-closure-sample and a compiled-from-head closure compiler :P

**Comment by TimvdLippe** [comment]
Ah that explains why my closure gulp task was not working yesterday and I couldn't find an update on npm. Thanks!

**Comment by azakus** [comment]
The next release of closure-compiler should have the `---polymer_version=2` flag supported.

**Pull request merged**
