### PR TITLE
[0.8] Allow a computed value to have multiple dependencies

### LINKED ISSUE #1092: 0.8-preview: multiple arguments to computed method
http://jsbin.com/gotosa/4/edit?html,output

```js
Polymer({
  // ...
  computed: {
    sum: 'add(num1,num2)'
  }
  // ...
});
```

### PR DESCRIPTION
**Pull request by peterwmwong**
Fixes #1092

I see that 0.8 is still in early stage development and will totally understand if you guys choose not to pull this in.

Thanks.

### CODE REVIEW

**Comment by addyosmani** [comment]
cc @sjmiles

**Comment by addyosmani** [comment]
Please note that this now needs to be rebased.

**Comment by peterwmwong** [comment]
@addyosmani Thanks, done.

**Comment by peterwmwong** [comment]
Closing as it appears to now be handled with the new asynchronous computed properties [commit](https://github.com/Polymer/polymer/commit/9d5ee38f025e10f9f180682f1cf736ef2c786338)

**Pull request closed without merging**
