### PR TITLE
Change 'Polymer Project Authors' to 'Polymer Authors'

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@notwaldorf, @kevinpschaaf @azakus, @sorvell, @justinfagnani, PTAL.

**Comment by TimvdLippe** [comment]
@FluorescentHallucinogen the Polymer team is very busy preparing for Google IO. The response time on pull requests has thus been increased. Please wait patiently until they have time to take a look at yours, thanks!

**Comment by FluorescentHallucinogen** [comment]
@TimvdLippe Will Polymer 2.0 be released before or during Google I/O 2017? All pull request related to `bower.json` and `package.json` should be merged before the release.

**Comment by TimvdLippe** [comment]
It is up to the Polymer team to determine which changes must be
incorporated in Polymer 2.0 before launch. There is no release date
announced thus far; I can only guess thst on IO we hear more about that.

**Comment by TimvdLippe** [comment]
To maintain a clean history, please combine your pull requests together in one pull request that we can then merge. We can not accept the changes to the license, so please leave these changes out of the combined pull request.

**Pull request closed without merging**
