### PR TITLE
Do not reflect properties starting with an uppercase letter

### LINKED ISSUE #3500: reflected properties with leading upper case letter throw exceptions
#### Live Demo

http://jsbin.com/mocakesixa/edit?html,console,output

### Versions

- Polymer: v1.3.1

### PR DESCRIPTION
**Pull request by azakus**
Add tests for uppercase properties

Fixes #3500

### CODE REVIEW

**Comment by azakus** [comment]
Rather than try to work around `setAttribute` not accepting leading '-' characters by trimming the leading character, which could lead to odd collisions if two or more elements shared similar property names, @kevinpschaaf suggested that we instead warn that properties starting with an uppercase character will not reflect to attributes.

Also handle weird attribute bindings like `-u-p-p-e-r-c-a-s-e$=` by warning.

**Comment by TimvdLippe** [comment]
I like that suggestion a lot!

**Comment by azakus** [comment]
@kevinpschaaf PTAL

**Comment by kevinpschaaf** [comment]
LGTM

**Pull request merged**
