### PR TITLE
Use stricter binding parsing for efficiency and correctness.  Fixes #2705

### LINKED ISSUE #2743: _bindingRegex + _parseBindings erroneously removing template contents
As demonstrated in the following Plunker the current regex employed by _bindingRegex fails to appropriately parse the `{` to begin the object notation in the template when employed in _parseBindings.  Here I've replaced the character with a property binding but that's no good...

http://plnkr.co/edit/wzKmEx34SDmVsR9B5WvI?p=preview

Code inline:
```
<dom-module id="x-test">
	     <template>
	         {
	          "@context": "http://schema.org"
	          "@type": "ImageObject",
	          "author": "[[author]]"
	         }
	       <br/>
	       [[hack]]
	          "@context": "http://schema.org"
	          "@type": "ImageObject",
	          "author": "[[author]]"
	         }
	     </template> 
	  </dom-module>
	  <script>
	  Polymer({
    is: 'x-test',
    properties: {
      author: {
        type: String,
        value: 'test'
      },
      hack: {
        type: String,
        value: '{'
      }
    }
	  });
	  </script>
</dom-module>
```

### PR DESCRIPTION
**Pull request by kevinpschaaf**
Based on discussion and work in https://github.com/Polymer/polymer/pull/2711.

Also fixes #2743.

### CODE REVIEW

**Comment by JeremybellEU** [comment]
Closing #2711 
I would like to review this PR, but don't have time till tomorrow noon. First impression is looking good!

**Comment by david-saslawsky** [comment]
Amazing :+1: the performance increase is an unexpected bonus.

Using regexp for parsing feels like being a drunk Russian teenager with a GoPro. You either get awesome results or learn a valuable lesson.

<br>
The catastrophic backtracking is caused by the optional comma in `ARGUMENT_LIST` and is made worse by the ambiguity between `IDENT` and `NUMBER`.

`-123.0` is parsed as:
````
IDENT(-123.0)            // IDENT allows char, digits, '-' and '.'
IDENT(-123.) IDENT(0)    // because ',' is optional in argument list
....
....                     // same up to ...
IDENT(-) IDENT(1) IDENT(2) IDENT(3) IDENT(.) IDENT(0)
```` 

<br>
With a minor change on string escaping (should also accept `[[compute("\n")]]`) and the addition of space matching, the expression becomes:
````
var IDENT  = '(:?' + '[a-zA-Z_$][a-zA-Z0-9_.:$-]*'  + '\\s*' + ')'; 
var NUMBER = '(:?' + '[-+]?[0-9]*\.?[0-9]+(:?[eE][-+]?[0-9]+)?'  + '\\s*' + ')'; 
var SQUOTE_STRING = '(?:' + '\'(?:[^\'\\\\]|\\\\\.)*\''  + '\\s*' + ')';
var DQUOTE_STRING = '(?:' + '"(?:[^"\\\\]|\\\\.)*"'  + '\\s*' + ')';
var STRING = '(?:' + SQUOTE_STRING + '|' + DQUOTE_STRING + ')';

var ARGUMENT = '(?:' + IDENT + '|' + NUMBER + '|' +  STRING + ')';
var ARGUMENT_LIST =		'\\(\\s*' + 
    						'(?:' +
                        		'(:?' + '\\)\\s*' + ')' + '|' +  // no args
								'(:?' + ARGUMENT + '(:?,\\s*' + ARGUMENT + ')*' + ')' +
	    					 ')' +
						'\\)\\s*'; 

var COMPUTED_FUNCTION = '(?:' + IDENT + ARGUMENT_LIST + ')';
var BINDING = '(' + IDENT + '|' + COMPUTED_FUNCTION + ')';

var OPEN_BRACKET = '(\\[\\[|{{)'  + '\\s*';  // Group 1
var CLOSE_BRACKET = '(?:]]|}})';
var NEGATE = '(?:(!)\\s*)?'; // Group 2
var EXPRESSION = OPEN_BRACKET + NEGATE + BINDING + CLOSE_BRACKET;
````

This seem to work but a useless backtracking remains for `IDENT | IDENT(ARGS)`

**Comment by JeremybellEU** [comment]
Couldn't find any bug with the regex, apart from the `function('\n')` case of @david-saslawsky and performance seemed good.
LGTM!

**Comment by sorvell** [comment]
LGTM

**Pull request merged**
