### PR TITLE
Fix crlf across project

### LINKED ISSUE #2592: Cloning and editing Polymer on Linux machines causes diff clutter
When developing Polymer on a Linux machine, diff clutter is caused due to line-ending changes. In order to globally configure line-endings and prevent this clutter from happening, a .gitattributes file should be added.

Steps to reproduce (on a Linux machine):
1. Clone/Fork Polymer
2. Open the project in your prefered editor
3. Open a file with `\r\n` line-endings (currently on master: `src/lib/css-parse.html`)
4. Insert a character somewhere in the file
5. Save the file
6. Delete the just inserted character (e.g. no textual changes should remain)
7. Save the file
8. Run `git diff` and observe the output below:

```javascript
diff --git a/src/lib/css-parse.html b/src/lib/css-parse.html
index a176d7c..30c9bee 100644
--- a/src/lib/css-parse.html
+++ b/src/lib/css-parse.html
@@ -43,7 +43,7 @@ Polymer.CssParse = (function() {
             n = {start: i+1, parent: p, previous: previous};
             p.rules.push(n);
             break;
-          case this.CLOSE_BRACE: 
+          case this.CLOSE_BRACE:
             //console.groupEnd(n.start);
             n.end = i+1;
             n = n.parent || root;
@@ -84,9 +84,9 @@ Polymer.CssParse = (function() {
       if (r$) {
         for (var i=0, l=r$.length, r; (i<l) && (r=r$[i]); i++) {
           this._parseCss(r, text);
-        }  
+        }
       }
-      return node;  
+      return node;
     },
 
     // stringify parsed css.
@@ -99,10 +99,10 @@ Polymer.CssParse = (function() {
         if (r$ && (preserveProperties || !this._hasMixinRules(r$))) {
           for (var i=0, l=r$.length, r; (i<l) && (r=r$[i]); i++) {
             cssText = this.stringify(r, preserveProperties, cssText);
-          }  
+          }
         } else {
-          cssText = preserveProperties ? node.cssText : 
-            this.removeCustomProps(node.cssText);  
+          cssText = preserveProperties ? node.cssText :
+            this.removeCustomProps(node.cssText);
           cssText = cssText.trim();
           if (cssText) {
             cssText = '  ' + cssText + '\n';
@@ -138,7 +138,7 @@ Polymer.CssParse = (function() {
     },
 
     removeCustomPropApply: function(cssText) {
-      return cssText            
+      return cssText
         .replace(this._rx.mixinApply, '')
         .replace(this._rx.varApply, '');
     },
@@ -171,7 +171,7 @@ Polymer.CssParse = (function() {
   };
 
 
-  // exports 
+  // exports
   return api;
 
 })();
```
The actual changes are `^M` characters indicating the line-ending changed.
image

Currently if you want to get rid of these changes:
1. Add a `.gitattributes` in the top-level folder
2. In the file insert `* binary`
3. `git add .`
4. `git reset --hard`

However this makes you lose ALL changes you made.
Therefore to prevent diff clutter and being able to contribute on Linux machines, the `.gitattributes` file should be added with `* text=auto`

### PR DESCRIPTION
**Pull request by samccone**
Fixes #2592

Resolves #2484 #3164

### CODE REVIEW

**Comment by samccone** [comment]
@azakus here is the one off commit to resolve this issue once and for all

**Comment by samccone** [comment]
Let me know when we want to land this... Will update

**Comment by azakus** [comment]
Yeah, I'm still looking at a few PRs. Will let you know when the grand reset can occur :dancers:

**Comment by samccone** [comment]
no worries

**Comment by JeremybellEU** [comment]
Aw yeah, clean slate!

**Comment by kevinpschaaf** [comment]
@samccone We're endeavoring to get PR's triaged and merged this week, and then that would be a good time to rebase and merge this.  Thanks!

**Comment by samccone** [comment]
ok just let me know when :)

**Comment by azakus** [comment]
I'm just going to make this happen on master, thanks for the PR though!

**Comment by samccone** [comment]
yep

**Pull request closed without merging**
