### PR TITLE
Eliminate the need to write `:host ::content` instead of just `::content`

### PR DESCRIPTION
**Pull request by nazar-pc**
While keeping the same processing under the hood.
I've also removed workaround from tests and they don't fail, which is good.

### CODE REVIEW

**Comment by tjsavage** [comment]
Thanks for the PR - apologies for the delay on feedback. To make it a little easier to discuss the impetus and reasoning behind the change, would you be able to create an issue that goes over the reasoning and then link to it from this PR?

**Comment by nazar-pc** [comment]
It was already created and linked back: https://github.com/Polymer/polymer/issues/1727

**Comment by nazar-pc** [comment]
Just rebased this against master to resolve conflicts and did some small improvements.
Merge this small fix soon, please. It is almost 2 months old already.

**Comment by nazar-pc** [comment]
Rebased against master once again. Really simple fix, sad to see it is not merged months later :-1:

**Comment by sorvell** [comment]
LGTM. Sorry for the delay and thanks for the effort!

**Pull request merged**
