### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by e111077**
Used for running tests every push to the 3.0 preview branch.

DO NOT MERGE

Travis will continue to fail until WCT is updated to master

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Seems like CI is failing because the Travis config has not been updated.

**Comment by e111077** [comment]
List of related issues:
Polymer/polymer-modulizer#368

**Comment by e111077** [comment]
import href tests fail and will always fail.

**Comment by e111077** [comment]
Closed. working branch is `3.x-tests`

**Pull request closed without merging**
