### PR TITLE
Set latest firefox addon for testing

### PR DESCRIPTION
**Pull request by tomalec**
as Selenium - Firefox issue is now fixed SeleniumHQ/selenium/issues/2110

### Reference Issue

Fixes Polymer/polymer/issues/3760

### CODE REVIEW

**Comment by kevinpschaaf** [comment]
@azakus PTAL

**Comment by tomalec** [comment]
@tjsavage it also applies to 2.0-preview, should I provide a PR for 2.0 as well?

**Comment by chuckh** [comment]
Looks like WCT ignores Firebox versions greater than 46.0, so Firefox 47 or 48 won't be tested.  See https://github.com/Polymer/web-component-tester/issues/367.

**Comment by tomalec** [comment]
I have created new PR for 2.0-preview, that uses Windows 10 to run latest Firefox (https://saucelabs.com/platforms#windows8-10)
https://github.com/Polymer/polymer/pull/4059

**Comment by kevinpschaaf** [comment]
Closing, as we now test the latest version of Firefox on Travis.

**Pull request closed without merging**
