### PR TITLE
Exclude package.json file from Bower package

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@kevinpschaaf, @valdrinkoshi, @azakus, please merge this pull request.

**Comment by FluorescentHallucinogen** [comment]
@notwaldorf, please merge this pull request.

**Comment by FluorescentHallucinogen** [comment]
@notwaldorf, @kevinpschaaf @azakus, @sorvell, @justinfagnani, please merge this pull request.

**Comment by TimvdLippe** [comment]
To maintain a clean history, please combine your pull requests together in one pull request that we can then merge. We can not accept the changes to the license, so please leave these changes out of the combined pull request.

**Pull request closed without merging**
