### PR TITLE
2.0 mixin behaviors

### PR DESCRIPTION
**Pull request by sorvell**
Adds `Polymer.MixinBehaviors` to allow behaviors to be used with classes and optimizes legacy `Polymer({...})` syntax somewhat.

### CODE REVIEW

**Comment by miztroh** [comment]
@sorvell Can you provide an example of how to utilize existing behaviors inside a new class-based element definition?

**Comment by arthurevans** [comment]
@miztroh I believe this would be like this:

```
class XClass extends Polymer.mixinBehaviors([MyBehavior, MyBehavior2], Polymer.Element) {
  static get is() { return 'x-class'}

  ...
}
customElements.define(XClass.is, XClass);
```

The `mixinBehavior` function also mixes in the Legacy APIs, the same as if you extended `Polymer.LegacyElement`. These APIs are required since since hybrid behaviors depend on them.

**Comment by miztroh** [comment]
@arthurevans Thanks!

**Comment by arthurevans** [comment]
I think this should resolve issue #4181? @kevinpschaaf

**Pull request merged**
