### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by nazar-pc**

### CODE REVIEW

**Comment by samccone** [comment]
lgtm :+1:

**Comment by ebidel** [comment]
:bomb: :boom:

**Comment by samccone** [comment]
thanks again @nazar-pc :clap:

**Comment by nazar-pc** [comment]
Yeah, this PR was awesome.
Any chance for other 9 to be considered in near future?
They are different in size and content, the oldest is also from 5th of August, but I hope at least bugfixes may land soon.

**Pull request merged**
