### PR TITLE
0.8 gestures

### PR DESCRIPTION
**Pull request by frankiefu**

### CODE REVIEW

**Comment by arthurevans** [comment]
What did we just add here? And is this in 0.8, or post-0.8?

**Comment by frankiefu** [comment]
This is wip gesture system (currently on-tap and on-track are somewhat supported).  @azakus will continue to work it next week.  My understanding is this is not part of the 0.8 official release.  @sorvell can confirm.

**Comment by peterwmwong** [comment]
FYI - I noticed that the track gesture introduced in this PR breaks touch scrolling.  [PolymerElements/paper-drawer-panel](https://github.com/polymerelements/paper-drawer-panel) content cannot be scrolled on mobile devices because the track gesture is calling `preventDefault()` on touch move [here](https://github.com/Polymer/polymer/pull/1309/files#diff-051391d48752db6ed28755b4c2fdf5c0R208).

Reduction: http://jsbin.com/wocoba/12/edit?html,output vs http://jsbin.com/wocoba/13/edit?html,output

**Comment by azakus** [comment]
This should be addressed by the complete gestures rewrite in #1486

**Pull request merged**
