### PR TITLE
Add test for parsing multi-line css comments

### LINKED ISSUE #2455: CSS in comments is not ignored by Polymer.
```
      /*paper-submenu::shadow paper-item::shadow iron-icon {
        position: absolute;
        top: 4px;
      }*/
```

Just an example, the above CSS continued to be perpetuated to the element despite comments.

### PR DESCRIPTION
**Pull request by JeremybellEU**
Closes #2455 

Tests pass locally, but have to see what CI reports, else the issue requires additional information on how to reproduce the fault.

### CODE REVIEW

**Comment by JeremybellEU** [comment]
image

Picture from the http://www.regex101.com match. The tests do not appear to fail on the added testcase, they are failing on other tests.

**Comment by samccone** [comment]
:+1: LGTM

**Comment by samccone** [comment]
@JeremybellEU Thanks for this work, really is appreciated

**Comment by JeremybellEU** [comment]
No problem. Glad I could leverage some of the investigation work for the bug reports.

**Pull request merged**
