### PR TITLE
WIP: First attempt at generated TypeScript declarations. Not there yet.

### PR DESCRIPTION
**Pull request by justinfagnani**

### CODE REVIEW

**Comment by justinfagnani** [comment]
@azakus FYI. The generator I'm writing here can be adapted to generate the Closure mixin boilerplate. Check out the mixin interfaces.

**Comment by jfrazzano** [comment]
How cool that is exactly what I am doing.  Am trying to use a descriptor to pass whole sets of behavior and design… using a reg-ex parser to find patterns in the css I don’t see… would have to be able to tell it what was functionally the same though. Am racing to see yours

**Comment by nbransby** [comment]
ETA on this one?

**Comment by TimvdLippe** [comment]
This PR has been superseded by #4928 as result of development of https://github.com/Polymer/gen-typescript-declarations Subscribe to #4928 for updates about TypeScript support 🎉

**Pull request closed without merging**
