### PR TITLE
Fix: There is no effect of kind 'computedAnnotation'

### PR DESCRIPTION
**Pull request by kaste**
Although `computedAnnotation` is the better name, you actually named it `annotatedComputation`.

### CODE REVIEW

**Comment by azakus** [comment]
Please add a test case that tests the problem this PR is fixing. See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#running-the-polymer-library-unit-tests) for more details.

**Comment by kaste** [comment]
Sorry for not giving a description. I just thought this is a simple oversight. 
Did you take a look at the context of this patch? It's about the order effects are applied. Right now order is undefined. Unfortunately, because of this kind of error and how Polymer is written (not in testable units), this feature cannot be tested. AFAIK at least. :wink: 

Bug:
 
fx-order-before

Fix:

fx-order-after

**Comment by TimvdLippe** [comment]
You can test this feature by creating several effects and update a property. Then verify that the effects are propagated in order as expected

**Comment by kaste** [comment]
AFAIK I can't just create effects and plug them to an element. For the
observers it's doable, but the annotations type is.. well complex.

In which file should I put the test?

Tim van der Lippe <notifications@github.com> schrieb am Do., 4. Feb. 2016
16:23:

**Comment by TimvdLippe** [comment]
You can define an element which has a property with an observer. Then a child element with a property also observable and bound to the parent. A computed function on a different parent property and inside the function you can check the order. Then a div with textcontent a computed property. I think you got all the effects then, currently on mobile so cant verify.

I would put the test in test/unit/bind (with dom-modules defined in test/unit/bind-elements)

**Comment by TimvdLippe** [comment]
@kaste @azakus I have submitted a test suite for this PR here: https://github.com/kaste/polymer/pull/1

If Azakus accepts this test suite, Kaste you should merge the PR on your repo and then this PR should be automatically updated with the new commit. Then Azakus could merge it.

**Comment by kevinpschaaf** [comment]
This is great, thank you @TimvdLippe and @kaste!

LGTM :100:

**Pull request merged**
