### PR TITLE
Add travis config

### PR DESCRIPTION
**Pull request by azakus**
Set up travis to test chrome and linux always, and all of our supported browsers
for first-party PRs.

### CODE REVIEW

**Comment by azakus** [comment]
After this pull, I will disable our homegrown CI runner for polymer.

**Comment by samccone** [comment]
Woot!

**Comment by azakus** [comment]
As you can see, Travis and our homegrown CI server agree that IE 10 is crazy. My current best guess here is that this is related to the polyfilled MutationObserver.

Disturbingly, IE 10 works just like the rest if you run wct and sauce manually behind the $GOOG corporate proxy, so that leads me to thing this weird quirk is also networking related.

**Comment by samccone** [comment]
@azakus if you add something like this
https://github.com/tastejs/todomvc/commit/abee8bdedb4913a6f70b4ad5167fad16ad333def

It should make CI super super easy to debug, it was a huge win for us over in todomvc land

**Comment by kevinpschaaf** [comment]
LGTM

**Pull request merged**
