### PR TITLE
ES5 strict doesn't like function declarations inside inner blocks.

### PR DESCRIPTION
**Pull request by rictic**
(review changes with [github's whitespace-ignoring view](?w=1) to reduce the solid-green diff line-ending fight)

### CODE REVIEW

**Comment by rictic** [comment]
This came up with some code that compiled everything down to one 'use strict' file, and jscompiler becomes quite unhappy in that case.

**Comment by samccone** [comment]
to be clear the error here is that because there was not var, fn was being defined in the global scope.

I wonder if integrating a tool like jshint or jscs or eslint or (whatever tool here) could prevent these kind of issues in the future.

**Comment by rictic** [comment]
The function declaration wasn't pulled up to global scope, but in non-strict code it's hoisted to the top of the containing function, whereas in strict code it's only defined in its containing block.

Closure compiler probably throws the error here because this behavior can be confusing. The original code here isn't wrong, in strict mode or in lax mode.

**Comment by samccone** [comment]
screenshot from 2015-11-23 12 50 07

hmm interesting! there must be another fn defined somewhere I guess

**Comment by rictic** [comment]
Try:

function lax() {if (true) { function g() {return 'yes';}} return g()}
function strict() {'use strict'; if (true) { function g() {return 'yes';}}
return g()}

lax(); // "yes"
strict(); // throws ReferenceError

**Comment by azakus** [comment]
LGTM

**Pull request merged**
