### PR TITLE
Use correct version

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@ChadKillingsworth What you mean? This patch updates the version in `package.json`.

**Comment by ChadKillingsworth** [comment]
Sorry - missed the `package.json` when I looked at the diff. 👍

**Comment by FluorescentHallucinogen** [comment]
@azakus Please also merge:

https://github.com/webcomponents/webcomponentsjs/pull/707
https://github.com/webcomponents/custom-elements/pull/69
https://github.com/webcomponents/shadydom/pull/102
https://github.com/webcomponents/shadycss/pull/62

**Comment by FluorescentHallucinogen** [comment]
@azakus And https://github.com/webcomponents/webcomponents-platform/pull/7

**Comment by FluorescentHallucinogen** [comment]
@azakus And https://github.com/webcomponents/webcomponents-platform/pull/8 :)

**Comment by FluorescentHallucinogen** [comment]
@azakus And https://github.com/webcomponents/html-imports/pull/45 :-D

**Comment by FluorescentHallucinogen** [comment]
@azakus And https://github.com/webcomponents/template/pull/11

**Comment by FluorescentHallucinogen** [comment]
@azakus https://github.com/webcomponents/custom-elements/pull/74

**Pull request merged**
