### PR TITLE
v3.4.0 release notes and commit list

### PR DESCRIPTION
**Pull request by bicknellr**
Adds release notes for all the new and changed behavior I could find in the `legacy-undefined-noBatch` branch. ~~I still need to collect some more info about the feasibility of new behavior around constructable stylesheets.~~ *(This behavior is now behind a flag: `useAdoptedStyleSheetsWithBuiltCSS`.)*

- [x] Merge #5645 and update this PR
- [x] Release Polymer
- [x] Add commit list

### CODE REVIEW

**Comment by bicknellr** [comment]
I added a section on `useAdoptedStyleSheetsWithBuiltCSS`, PTAL

**Comment by bicknellr** [comment]
I was just trying out `./util/gen-changelog.sh` and it puts commit messages in a list above the old changelog content. I'd like to put these above the raw list of commits, so I wonder if this PR would be better if it went into master as part of the typical post-release changelog commit rather than editing the changelog as part of this branch?

**Comment by bicknellr** [comment]
Is that fix enabled by default? (i.e. unrelated to if `reuseChunkedInstances` is set)

**Comment by kevinpschaaf** [comment]
Right, it's an unconditional fix to a behavior that regressed in Polymer 2/3 vs. Polymer 1.

**Comment by bicknellr** [comment]
Ok, added, PTAL. Also, what do you think about the PR-moving situation I mentioned earlier?

**Comment by bicknellr** [comment]
Ok, I'll wait until https://github.com/Polymer/polymer/pull/5497 is released and then add the commit log to this PR.

**Pull request merged**
