### PR TITLE
Revert style properties change

### PR DESCRIPTION
**Pull request by rictic**
From fd5778470551f677c2aa5827398681abb1994a88

This broke a number of tests on an internal project.

### CODE REVIEW

**Comment by sorvell** [comment]
LGTM.

Our plan is to investigate the breaking tests and try to get this changed merged back asap.

**Comment by nazar-pc** [comment]
This is a huge breaking change for many people. As I understand this was not fixed back before release and now implementation does not correspond to specification, am I right?

Your internal projects are awesome, but many people rely on things that were fixed. I suspect correcting of styles order should be enough in mentioned projects. It should be done anyway.

**Comment by samccone** [comment]
@rictic is there anyway you can post test cases?

**Comment by sorvell** [comment]
Unfortunately, there is a flaw in the css shimming for custom properties.
Consider:

<x-foo class="bar"></x-foo>

We shim the `:host` styles of the element via an `x-foo` selector. This
allows a user's style made with a `.bar` selector to properly override the
`:host` styling. However, when custom properties are shimmed, we make a
selector like `x-foo.x-foo-0` for the custom property styling. This
selector *improperly* overrides the user's `.bar` selector.

Placing more styling inside the stylesheet for custom properties exposes
more styling to this flaw. This is what the PR that we reverted did.

We're considering if there is an alternate method of shimming that avoids
this problem. We're also considering adding an option to flip the shimming
behavior between before and after this PR to give users the option to
choose what works best for them.

**Comment by nazar-pc** [comment]
Is there any new test that I can use to improve implementation? Currently I see that existing test was removed, but nothing added instead.

**Comment by sorvell** [comment]
The flaw is in the design of the custom property shimming. The PR simply
put more pressure on this by exposing more styling to this flaw. This bin
shows the basic problem:

http://jsbin.com/jisuxo/edit?html,output

**Comment by nazar-pc** [comment]
I'll try to find some relatively easy solution for this to cover both of mentioned cases.

**Comment by sorvell** [comment]
Excellent. Thanks for your help.

**Comment by sorvell** [comment]
See also: https://github.com/Polymer/polymer/issues/3326

**Pull request merged**
