### PR TITLE
Use ESLint for Polymer

### PR DESCRIPTION
**Pull request by azakus**
Modified version of #2600

- Ignores experimental and demo folders
- A few style tweaks
- Rename gulp task to `gulp lint`, and cause it to emit non-zero status
 for travis testing

Thanks to @fredj for the base PR

### CODE REVIEW

**Comment by azakus** [comment]
Googlebot, stand down!

**Comment by TimvdLippe** [comment]
:+1:

One question that popped up: how many errors are reported? If there is a large amount of errors, will there be some sort of clean sweep? (In a similar fashion to the line-endings)

**Comment by fredj** [comment]
@googlebot I confirm that I am okay with these commits being contributed to Google

**Comment by azakus** [comment]
@TimvdLippe there's around 63 linter errors, mostly around variable redeclaration. I'll make another PR to clean that up.

@sorvell, @kevinpschaaf, @sjmiles PTAL

**Comment by azakus** [comment]
@TimvdLippe Actually, I might as well fix them all in this PR

**Comment by kevinpschaaf** [comment]
LGTM

**Comment by abdonrd** [comment]
@azakus @kevinpschaaf maybe update ESLint extending official Google config?

https://github.com/google/eslint-config-google

**Comment by azakus** [comment]
@abdonrd We had ~4000 lint error last I tried with that config, and I'm not super interested in fixing them :no_good:

**Comment by abdonrd** [comment]
@azakus okey! jaja :grin:

**Pull request merged**
