### PR TITLE
Replace the suffix '-changed' by Polymer.Base._EVENT_CHANGED

### LINKED ISSUE #3643: Replace the suffix '-changed' by Polymer.Base._EVENT_CHANGED
### Description

There are several references to `'-changed'` in the code and exist a constan in `Polymer.Base` called `_EVENT_CHANGED`. It would be a good idea centralize the suffix in one place.
#### Live Demo

N/A
#### Steps to Reproduce

Find `'-changed'` in all project.
#### Expected Results

Use `Polymer.Base._EVENT_CHANGED` everywhere.
#### Actual Results

The suffix `'-changed'`appear in 4 times in 3 files.
### Browsers Affected

N/A
### Versions
- Polymer: v1.4.0 and below.
- webcomponents: N/A

### PR DESCRIPTION
**Pull request by jorgecasar**
### Reference Issue

Close #3643

### CODE REVIEW

**Comment by felixzapata** [comment]
+1

**Comment by sergicontre** [comment]
+1

**Comment by eduardosada** [comment]
+1

**Comment by TimvdLippe** [comment]
This property was removed in Polymer 2. A quick search shows that `-changed` is used twice in `property-effects`. It would be okay to have a local variable for that, so feel free to publish a PR with that change.

**Pull request closed without merging**
