### PR TITLE
Should camelize id names when creating this.$ automatic node finding object.

### PR DESCRIPTION
**Pull request by dotDeeka**
I mentioned this in issue #1747 .

This PR would not make a breaking change. In order for ids with dashes to be camelized you would have to opt in by setting camelizeIds: true in your element.

```html
  <dom-module id="my-cool-element">
    <template>
      <div id="foo-element"></div>
    </template>
  </dom-module>
```
```javascript
Polymer({
  is: 'my-cool-element',
  camelizeIds: true,
  ready: function () {
    this.$.fooElement.innerHtml = 'foo';
  }
});
```
I wanted to figure out a way to set this config globally but I'm not sure if that makes sense.

This is the first PR I'm proposing to Polymer so please let me know if I should be doing anything differently.

Feedback appreciated.

### CODE REVIEW

**Comment by dotDeeka** [comment]
I signed it!

**Comment by samccone** [comment]
hey @dotDeeka great call on this one and great call on putting it behind a flag until we bump to 2.0, I agree this is totally confusing at the moment, given how we automagically do this with attributes I think that this falls totally inline :+1: .

cc @ebidel for :eyes:

**Comment by dotDeeka** [comment]
@samccone Other than the fact that 2 tests are failing at the moment, does this implementation look ok, or is there something different you guys would like to see? Thanks.

**Comment by samccone** [comment]
@dotDeeka The final :+1: :-1: is actually not up to me, going to defer to @tjsavage and team for final decision

**Comment by dotDeeka** [comment]
Cool.

**Comment by kevinpschaaf** [comment]
We use dash-case in _attribute names_ in which case information is lost by the parser, but since node id's are case-sensitive, there is no technical reason this is required (as spelled out in https://github.com/Polymer/polymer/issues/1747#issuecomment-150313046).  From a simplicity point of view we are electing to close this.

**Pull request closed without merging**
