### PR TITLE
Polymer 1: Allow arbitrary whitespace in CSS imports 

### PR DESCRIPTION
**Pull request by freshp86**
This is a port of https://github.com/Polymer/polymer/pull/4780 for Polymer 1.

### CODE REVIEW

**Comment by freshp86** [comment]
/cc @sorvell @kevinpschaaf 

It would be nice if this fix can be ported to Polymer 1, so that we (in Chromium) can avoid errors like [this one](https://chromium-review.googlesource.com/c/chromium/src/+/734861) as well as having to add multiple comments in the code, like [these](https://cs.chromium.org/search/?q=polymer/pull/3668&type=cs).

**Comment by freshp86** [comment]
Ping. Can someone take a look?

**Comment by freshp86** [comment]
Thanks for merging. Can we spawn a release for v1.11.1 so that this fix can eventually make it in Chromium?

**Comment by freshp86** [comment]
@azakus Is this included in a released version of Polymer 1 yet? If not, are there any plans to make one? Otherwise this fix can't be leveraged in our Chromium code.

**Comment by azakus** [comment]
No sorry, its been too long since a release was cut. I'll try to make one today!

**Pull request merged**
