### PR TITLE
Nazar-pc fix for #2348

### LINKED ISSUE #2348: Getters and setters made inaccessible
```javascript
Polymer({
	'is'		: 'cs-nav-tabs',
	'extends'	: 'nav',
	properties	: {
		active	: {
			observer	: 'active_changed',
			type		: Number
		}
	},
	ready : function () {
		if (!this.querySelector('button[active]')) {
			this.active = 0;
		}
	},
	active_changed : function () {
		var buttons = this.querySelectorAll('button');
		var button;
		for (var index = 0; index < buttons.length; ++index) {
			button = buttons[index];
			button.active = index == this.active;
		}
	}
});
```
```javascript
Polymer({
	'is'		: 'cs-button',
	'extends'	: 'button',
	properties	: {
		active	: {
			reflectToAttribute	: true,
			type				: Boolean
		}
	}
});
```
```html
<nav is="cs-nav-tabs">
	<button is="cs-button" type="button">One</button>
	<button is="cs-button" type="button">Two</button>
</nav>
```

At the moment when `button.active` is assigned (at `createdCallback` of `[is=cs-nav-tabs]`, you know), there are no getters/setters yet in `button` element, which eventually makes accessors below this newly declared property in prototypes chain and basically inaccessible.

**Firefox Nightly, Shadow DOM polyfill**

### LINKED ISSUE #2562: Setting properties before upgrade overrides Polymer's setters using the polyfill.
Please try this jsbin in safari: http://jsbin.com/zifigi/edit?html,output.  The code for x-example is available in https://gist.githubusercontent.com/blasten/861b640568f8b8268f89/raw/b6eab660b4cf6e439404e310e921f1cd5e27ae05/x-example.html

### PR DESCRIPTION
**Pull request by sorvell**
Fixes #2348.
Fixes #2562.

### CODE REVIEW

**Comment by sorvell** [comment]
This will also fix #2562.

**Comment by sorvell** [comment]
We'll need to avoid doing this on IE10. The custom elements polyfill uses a mixin strategy that makes this fix unfeasible.

**Comment by kevinpschaaf** [comment]
@googlebot CLA granted via https://github.com/Polymer/polymer/pull/2349.

**Comment by kevinpschaaf** [comment]
LGTM

**Pull request merged**
