### PR TITLE
[2.x] Move Firefox testing to sauce (windows), to test with latest Firefox

### PR DESCRIPTION
**Pull request by tomalec**
### Reference Issue

Fixes Polymer/polymer#3760

Related to old PR https://github.com/Polymer/polymer/pull/3761

### CODE REVIEW

**Comment by TimvdLippe** [comment]
I think this means that pull requests are not built with Firefox anymore, can you revert that change?

**Comment by tomalec** [comment]
Thanks for quick respons! :)
Is that what you mean?

**Comment by TimvdLippe** [comment]
I suppose so, at least it does not regress for pullrequests 😄 

You might want to bump Firefox to latest too while you are at it?

**Comment by tomalec** [comment]
It's here https://github.com/Polymer/polymer/pull/3761

**Comment by kevinpschaaf** [comment]
Closing, as we now test the latest version of Firefox on Travis.

**Pull request closed without merging**
