### PR TITLE
Fixes #4084: distribution on binded slot name.

### LINKED ISSUE #4084: Binded slot name do not distribute content as expected in Polymer#1.7.0
### Description

Binded slot name do not correctly distribute slotted elements on non-chromium browser
#### Live Demo

http://jsbin.com/denumizugi/edit?html,console,output
#### Steps to Reproduce

Create a slot using binding for the name : `<slot name="[[slotName]]"></slot>`
#### Expected Results

Nothing should be displayed
#### Actual Results

'Should not be assigned' is displayed on non-chromium browser
### Browsers Affected

- [ ] Chrome
- [x] Firefox (flashes)
- [x] Edge
- [x] Safari 10
- [x] Safari TP Release 15 (Safari 10.1, WebKit 12603.1.8)
- ? Safari 9
- ? Safari 8
- [x] IE 11
### Versions

- Polymer: v1.7.0
- webcomponents: v0.7.22

I wanted to do `<slot name$="[[slotName]]"></slot>` but is failed converting to `<content select$="[slot=[[slotName]]]"></slot>`. So the converted binding looks like `<content select="[slot=[[slotName]]]"></slot>`. Therefore, when the binding occurs, it sets 'select' as a property instead of an attribute on non-chrome browser (that do not natively support v0 web components). During distribution, the `_matchesContentSelect` function 

``` javascript
var select = contentElement.getAttribute('select');
if (!select) {
  return true;
}
select = select.trim();
if (!select) {
  return true;
}
```

returns always true.

### PR DESCRIPTION
**Pull request by hypnoce**

### CODE REVIEW

**Comment by hypnoce** [comment]
Hi team,

does this PR look good to you ?

Thanks

**Comment by hypnoce** [comment]
Hi team,

Should we close or merge this PR ?
We are waiting for it to switch to 2.0.

Thanks

François

**Comment by web-padawan** [comment]
@hypnoce I think you should use attribute binding: `<slot name$="[[slotName]]">`  
If it works, this PR is obsolete.

**Comment by TimvdLippe** [comment]
@web-padawan is correct. You should use `name$=` to get this behavior: http://jsbin.com/quhihetafo/edit?html,output

**Pull request closed without merging**
