### PR TITLE
[wip] Lint the javascript code with eslint

### PR DESCRIPTION
**Pull request by fredj**
Display errors with ```gulp lint```

work in progress

### CODE REVIEW

**Comment by BLamy** [comment]
Should probably be called `gulp eslint` as I would expect `lint` would be reserved for polylint once they fit that into the toolchain.

**Comment by fredj** [comment]
http://jscs.info/ should probably used instead as it's already the linter used in https://github.com/PolymerElements/polymer-starter-kit

**Comment by LM450N** [comment]
:+1: for following the validation rules of the PSK. If you prefer ESLint maybe you could propose it for the PSK then add the `eslint` task to Polymer.

**Comment by azakus** [comment]
Thanks for the PR!

I'm marking this as needs investigation and/or docs to make sure we evaluate linters for the best use case.

Is the community collecting around eslint the best, or is jshint, xo, jscs, etc. the best?

**Comment by azakus** [comment]
Alright, after reviewing other linters in #3368, I think eslint is the way to go!

I have a few tweaks I want to make on this PR, so I'm going to merge it into a different branch and close this one. I'll reference it when it's ready.

Thanks again!

**Pull request closed without merging**
