### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by kevinpschaaf** [comment]
We may use this for tooling or other future uses.

**Comment by kkirsche** [comment]
Interesting choice. Not sure why you'd want to rely on something which they say to leave out and isn't even used, but to each their own. Best of luck

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by IntranetFactory** [comment]
We use it in our build process, so I'd prefer it it stays there and is maintained.

**Pull request closed without merging**
