### PR TITLE
3430 - ie memory leak fixes - disable event caching, fixed resolver u…

### LINKED ISSUE #3430: Polymer will lead to memory leaks in Internet Explorer 11.
Polymer will lead to memory leaks in Internet Explorer 11. 
1. e.g  "open site "https://www.polymer-project.org/1.0/" in  Internet Explorer 11
2. then refresh page some times ， observe the system ram， would raise up constantly

### PR DESCRIPTION
**Pull request by bbsteventill**
### Reference Issue

…rl adding to root doc, and weak map ie issues

### CODE REVIEW

**Comment by bbsteventill** [comment]
I signed it!

Bloomberg has added me to their cla

reply@reply.github.com " data-digest="From: reply@reply.github.com " style="">

**Comment by domrongpon-tanpaibul** [comment]
Our team found this problem and this patch helps to solve the problem (partially).

Another issue that causes the leak is HTML Import and we do a workaround by copying components.html to the main page.

Using both solutions together can significantly reduce the leak in IE, even though not totally fixed. 

If this patch can be released at earliest, that would be great.

**Comment by bbsteventill** [comment]
FYI https://github.com/webcomponents/webcomponentsjs/pull/644 fixes the memory leaks within web components

**Comment by domrongpon-tanpaibul** [comment]
thanks @bbsteventill !

**Comment by sorvell** [comment]
@azakus can you please review this? Thanks.

**Comment by jay8t6** [comment]
@azakus @sorvell when is the next release coming out? I'd love to see the performance improvement in IE.

**Pull request merged**
