### PR TITLE
Do not surround empty textnodes with span tag (dom-if)

### PR DESCRIPTION
**Pull request by LM450N**

### CODE REVIEW

**Comment by LM450N** [comment]
I would love to run again the tests. Because the first time only IE10 on Windows 7 failed. Can you re-run them please ?

**Comment by LM450N** [comment]
PR #2058 does the job.

**Comment by sorvell** [comment]
Thanks for the PR.

Since this was so simple and it needed a test, we went ahead and just did it via https://github.com/Polymer/polymer/pull/2058.

**Comment by LM450N** [comment]
No problem. I do my best but you know, Google engineers will always be the best. :wink:

**Pull request closed without merging**
