### PR TITLE
[1/2] Add keywords

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@kevinpschaaf, @valdrinkoshi, @azakus, please merge this pull request.

**Comment by notwaldorf** [comment]
needs a rebase

**Comment by abdelq** [comment]
@notwaldorf You should be able to do it yourself, either using git or straight from Github.

See: https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by notwaldorf** [comment]
@abdelq Thank you, I know what a rebase is :)
There are 20 more like this PR that need rebases, and I don't really have time to do all of them :)

**Comment by FluorescentHallucinogen** [comment]
@notwaldorf 
> Needs a rebase

Done.

**Comment by FluorescentHallucinogen** [comment]
@notwaldorf, @kevinpschaaf @azakus, @sorvell, @justinfagnani, please merge this pull request.

**Comment by TimvdLippe** [comment]
To maintain a clean history, please combine your pull requests together in one pull request that we can then merge. We can not accept the changes to the license, so please leave these changes out of the combined pull request.

**Pull request closed without merging**
