### PR TITLE
Allow newlines in computed binding argument list

### PR DESCRIPTION
**Pull request by mgiuffrida**
This allows breaking in the middle of computed bindings, e.g.:

```
<div hidden$="[[_someVeryLongFunctionName(
                  someVeryLongArg,
                  anotherCrazyLongArg]]">
```

Note that `[\s\S]*` [doesn't seem to have worse performance]( http://jsperf.com/javascript-multiline-regexp-workarounds/5) than `.*`.

### CODE REVIEW

**Comment by samccone** [comment]
Hey @mgiuffrida awesome spot!!

Would you mind adding a new unit test here?
https://github.com/Polymer/polymer/blob/36b9fe034f5e67820a8aaca9020120415397cd15/test/unit/bind-elements.html

Thanks a million!!! :sparkles:

**Comment by mgiuffrida** [comment]
@samccone Done and they pass locally in Cr and FF. PTAL, thanks!

Chrome still limits HTML to 80 chars in WebUI so being able to break up long lines is helpful.

**Comment by samccone** [comment]
awesome work @mgiuffrida this LGTM :+1: 

ping @ebidel for :eyes:

**Comment by nazar-pc** [comment]
Nice addition

**Comment by mgiuffrida** [comment]
@danbeam for FYI

**Comment by david-saslawsky** [comment]
I can merge this fix into #2580 if that helps. 

Would be nice to get rid of the parsing oddities in computed bindings since they're frequently used in Polymer 1.0.

````
[[format(
    '[[D\'oh!]], "{0}" items left', 
    items.count
)]]
````

**Comment by nazar-pc** [comment]
There is even one more fix for this area: #2295

**Comment by david-saslawsky** [comment]
BTW, it looks like the intention in the original regular expression was to have a `\s*` before the `(` like this:

<pre>var m = expression.match(/([^\s]+)<b>\s*</b>\(([\s\S]*)\)/);</pre>

otherwise why use `[^\s]+` instead of `[^\(]+` ?

Maybe the expression should be:

````
var m = expression.match(/([^\s]+?)\s*\(([\s\S]*)\)/);
````
or
````
var m = expression.match(/([^\s\(]+)\s*\(([\s\S]*)\)/);
````

**Comment by TimvdLippe** [comment]
If I am not mistaken, this was added in #3017 with [`\\s*`](https://github.com/Polymer/polymer/pull/3017/files#diff-870cfe064a36c23b69e8da891fdff6beR98)

**Comment by mgiuffrida** [comment]
No, this still seems to be an issue: http://jsfiddle.net/mgiuffrida/x921yb0L/1/

As the expression has changed repeatedly since September, could someone from Polymer own this issue?

**Comment by kevinpschaaf** [comment]
We'll take a look at merging this; just need to make sure it's compatible with the first-level regex change in https://github.com/Polymer/polymer/pull/3017/files#diff-870cfe064a36c23b69e8da891fdff6beR92.

**Comment by mgiuffrida** [comment]
I'll give it a shot tonight.

**Comment by mgiuffrida** [comment]
I've opened #3370 and rebased there, my original repo was deleted.

**Comment by mgiuffrida** [comment]
Okay, I think this is right now? I always screw up GitHub pull requests...

**Comment by mgiuffrida** [comment]
triggering new build

**Comment by kevinpschaaf** [comment]
LGTM

**Comment by kevinpschaaf** [comment]
Thanks @mgiuffrida

**Pull request merged**
