### PR TITLE
Add change log file.

### PR DESCRIPTION
**Pull request by skywinder**
Hi, as I can see, you are carefully fill tags and labels for issues in your repo.

For such cases I create a [github_changelog_generator](https://github.com/skywinder/github-changelog-generator), that generate change log file based on **tags**, **issues** and merged **pull requests** from :octocat: Issue Tracker.

This PR add change log file to your repo (generated by this script).
You can check, how it is look like here: [Change Log](https://github.com/skywinder/polymer/blob/add-change-log-file/CHANGELOG.md)

Some essential features, that has this script:

-  it **exclude** not-related to changelog issues (any issue, that has label `question` `duplicate` `invalid` `wontfix` )
- Distinguish issues **according labels**:
    - Merged pull requests (all `merged` pull-requests)
    - Bug fixes (by label `bug` in issue)
    - Enhancements (by label `enhancement` in issue)
    -   Issues (closed issues `w/o any labels`)
- Generate neat Change Log file according basic [change log guidelines](http://keepachangelog.com).

You can easily update this file in future by simply run script: `github_changelog_generator Polymer/polymer` in your repo folder and it make your Change Log file up-to-date again!

Hope you find this commit as useful. :wink:

### CODE REVIEW

**Comment by skywinder** [comment]
Hmm.. some thing wrong with this file. The issues generated only for a last tag.. I will take a lot on it soon and will reopen PR as soon as I fix it.

**Comment by skywinder** [comment]
I signed it!

**Comment by skywinder** [comment]
Ok, the problem was in not encapsulated sign `<`. But change log is correct. I also run script with some customisations, to exclude some labels, that shouldn't be it change log (exclude your custom labels: `external issue`, `docs`, `pending-response`, `needs move`). Check it now - it look very neat!

the command, that I use is:

    github_changelog_generator --exclude-labels duplicate,question,invalid,wontfix,external\ issue,docs,pending-response,needs\ move

**Comment by azakus** [comment]
I'm not super satisfied depending on a ruby module (and dependencies) to print the changelog, but I'm also not super eager to make a good-enough version in node.

Therefore, I'll accept this PR, and make it a p3 issue to migrate to some node-based equivalent at a later time.

@skywinder is there a way to not generate the "unreleased" section? Ideally the CHANGELOG only updates on builds anyway.

**Comment by skywinder** [comment]
@azakus Thanks for feedback!

>Therefore, I'll accept this PR, and make it a p3 issue to migrate to some node-based equivalent at a later time.

I did [research of alternatives](https://github.com/skywinder/Github-Changelog-Generator/wiki/Alternatives), even node-based tools.  The most advanced tool is [#6](https://github.com/walmartlabs/generator-release) in my list. But it's so far from ideal change log generator. If you find some good node-based alternative - please, let me know!

>  is there a way to not generate the "unreleased" section? Ideally the CHANGELOG only updates on builds anyway.

Of course! Use `--unreleased-only` option for that! :wink: 
Here is a short [description of all options](https://github.com/skywinder/github-changelog-generator/wiki/Advanced-change-log-generation-examples)

Or just run `github_changelog_generator -h`.

**Comment by azakus** [comment]
Ok, I have a handle on this now. I've used a few different options, so I'll close this PR and add a changelog from your tool.

Thanks!

**Pull request closed without merging**
