### PR TITLE
Fix IE10 regressions. Fixes #2582

### LINKED ISSUE #2582: IE test regressions in dom-repeat, dom-bind, and dom-module-inline
IE tests have been failing due to an arcane timing bug in webcomponents-js, which have masked a couple of other bugs that have snuck in.

### PR DESCRIPTION
**Pull request by kevinpschaaf**
* Copy attribute list before modifying it
* Fall back to document for current document if no currentScript

### CODE REVIEW

**Comment by sorvell** [comment]
LGTM

**Comment by azakus** [comment]
Yeah, npm installs concurrently I believe, and wct also depends on bower. If bower is installing while wct is installing, npm assumes all the dependencies have loaded.

We've had bad lifecycle postinstalls like this in the past with selenium-standalone.

**Comment by samccone** [comment]
>  If bower is installing while wct is installing, npm assumes all the dependencies have loaded.

woah, sounds like a great bug to file over at https://github.com/npm/npm/

**Comment by azakus** [comment]
Here's a similar one: https://github.com/npm/npm/issues/7688

**Pull request merged**
