### PR TITLE
iterate behavior mixins in reverse order as the `hasOwnProperty` chec…

### PR DESCRIPTION
**Pull request by sjmiles**
…k means whoever goes _first_ wins

### CODE REVIEW

**Comment by sjmiles** [comment]
@cdata

**Comment by sjmiles** [comment]
This PR is faulty, don't merge until I can fix it.

**Comment by sjmiles** [comment]
Rebuilt this PR to actually do what it claims. Also added repairs for `hostAttributes` overriding and better tests. Note the test throws a warning in the console on purpose.

**Comment by kevinpschaaf** [comment]
Merged!

**Pull request merged**
