### PR TITLE
Remove trailing spaces

### PR DESCRIPTION
**Pull request by duykhoa**
This PR removes trailing spaces for some files and sets`no-trailing-spaces` as a required rule in eslint.

### CODE REVIEW

**Comment by duykhoa** [comment]
I signed it!

**Comment by fredj** [comment]
@duykhoa can you also add this rule to the ESlint config file so this error never show up again?
```diff
diff --git a/.eslintrc.json b/.eslintrc.json
index 634e0a6..a382981 100644
--- a/.eslintrc.json
+++ b/.eslintrc.json
@@ -5,6 +5,7 @@
   },
   "rules": {
     "no-console": "off",
+    "no-trailing-spaces": "error",
     "no-var": "error",
     "strict": "error",
     "valid-jsdoc": ["error", {
```

Thanks !

**Comment by duykhoa** [comment]
Hi @azakus, which branch should I base to?

**Comment by TimvdLippe** [comment]
@duykhoa the `master` branch. This PR targets the `1.x` branch atm.

**Comment by baocang** [comment]
@duykhoa I like this PR, but can you commits into`master` branch 😂

**Comment by duykhoa** [comment]
@baocang Can, I will make another PR.

**Pull request closed without merging**
