### PR TITLE
Fix an accidentally quadratic reduce(concat) in FlattenedNodesObserver

### PR DESCRIPTION
**Pull request by rictic**
Found by @mvanbem-goog debugging a perf issue in Gerrit

### CODE REVIEW

**Comment by rictic** [comment]
(still running internal tests, though I expect them all to pass)

**Review by kevinpschaaf — APPROVED** [review]
LGTM

**Comment by rictic** [comment]
All internal tests pass too.

**Comment by freshp86** [comment]
Is there any plan to push a new version that includes this fix? Asking since I am curious if this would result in any performance improvements in Chromium (for pages that still use Polymer like Settings and PrintPreview).

**Pull request merged**
