### PR TITLE
Fix for mixins declaration with space before colon

### PR DESCRIPTION
**Pull request by nazar-pc**
```css
--working-mixin: {
    color: red;
}
```
```css
--broken-mixin : {
    color: red;
}
```

With this fix both work fine.

### CODE REVIEW

**Comment by tjsavage** [comment]
Thanks for the pull request - apologies for the delay here. This looks like a solid fix - would you mind squashing the commits?

**Comment by nazar-pc** [comment]
Rebased against master and squashed into single commit.

**Comment by samccone** [comment]
:+1: lgtm

**Comment by samccone** [comment]
I think this should be good to go, @tjsavage anything else here?

**Comment by tjsavage** [comment]
LGTM - @azakus any idea why the tests would be failing?

**Comment by azakus** [comment]
It doesn't look like these tests have been run since our fix in webcomponentsjs for the failing IE tests.

**Comment by nazar-pc** [comment]
How to trigger it?

**Comment by azakus** [comment]
The IE failures are fixed with 1.2.0, this PR should pass after merging.

**Comment by azakus** [comment]
@nazar-pc already did. This PR was using the old homegrown CI, new PRs will use Travis CI.

**Comment by azakus** [comment]
Confirm IE 10 and IE 11 passing after merging with Polymer on master.

**Comment by azakus** [comment]
LGTM

**Pull request merged**
