### PR TITLE
Fix a typo in dom-if.html.

### PR DESCRIPTION
**Pull request by krozycki**
This fixes a small typo.

### CODE REVIEW

**Comment by bicknellr** [comment]
I think this is being used as shorthand for "if and only if" - there are [a few more instances](https://github.com/Polymer/polymer/search?q=iff) of 'iff' laying around.

**Comment by krozycki** [comment]
Well, will it be a good idea than, if I go on and unwrap these shorthands?

**Comment by arthurevans** [comment]
Yes, I think that's a good idea. "If and only if" is much clearer for the average reader.

**Comment by ebidel** [comment]
"iff" is pretty well known in the technical/scientific  community as "if and only if".

**Comment by krozycki** [comment]
So should I change this?

On Thu, Jul 21, 2016 at 17:22, Eric Bidelman <notifications@github.com> wrote:
"iff" is pretty well known in the technical/scientific community as "if and only if".

**Comment by kevinpschaaf** [comment]
I'll go ahead and rule that the [shorthand](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=define%3A%20iff) is fine as-is.

**Comment by arthurevans** [comment]
"Pretty well known" is not a great standard for terminology in API docs. Especially in a community like JavaScript developers, where many people are self-taught or don't have a traditional CS background. It's also extremely easy to overlook the repeated "f". 

From my own perspective, I've been coding and doing developer docs for 25 years now, but I'm largely self-taught as a coder. And the Polymer source is the *very first place* I have knowingly encountered this shorthand. And I only found the definition, by accident, after replacing several instances with "if," because I thought it was a typo.

I may be an anomaly, or I might not. But making it clear to the Arthurs of the world only costs 11 characters here, and I think that's a good tradeoff.

**Comment by krozycki** [comment]
Imho we should chamge it. It may not be obvious to everyone.

On Thu, Jul 21, 2016 at 18:27, Arthur Evans <notifications@github.com> wrote:
"Pretty well known" is not a great standard for terminology in API docs. Especially in a community like JavaScript developers, where many people are self-taught or don't have a traditional CS background. It's also extremely easy to overlook the repeated "f".

From my own perspective, I've been coding and doing developer docs for 25 years now, but I'm largely self-taught as a coder. And the Polymer source is the very first place I have knowingly encountered this shorthand. And I only found the definition, by accident, after replacing several instances with "if," because I thought it was a typo.

I may be an anomaly, or I might not. But making it clear to the Arthurs of the world only costs 11 characters here, and I think that's a good tradeoff.

**Comment by krozycki** [comment]
https://github.com/Polymer/polymer/pull/3794

**Comment by kevinpschaaf** [comment]
Ok, that's fair @arthurevans.  I stand overruled, and merged #3794!

**Pull request closed without merging**
