### PR TITLE
Enforce undefined rule for observers

### PR DESCRIPTION
**Pull request by kaste**
Enforce (again) the rule that observers are never called with undefined values. Basically reverts f68c30e21eec7d1fae04dc032c81df497444099e.
- Ensures observers on `*.splices` don't get undefined's initially. See #3239, https://github.com/Polymer/polymer/issues/2470#issuecomment-174199175
- Reduces confusion, e.g. #3401  
- Marks an invariant (dom-repeat sees unexpectedly undefineds) where it belongs, instead of masking it. Removes a confusing dependency between observers `marshalArgs` and `dom-repeat`.

### CODE REVIEW

**Comment by azakus** [comment]
At first glance, this looks like a breaking change to remove the ability to set `undefined`. At the point we'd be comfortable making a breaking change like this, we will probably reevaluate all of the databinding system.

**Comment by samccone** [comment]
while I like this change, this is going to be wildly breaking I fear

**Comment by MeTaNoV** [comment]
well, that's what is specified... :)

**Comment by kaste** [comment]
@azakus This has nothing to do with removing the ability to set `undefined`. The (simple) property observers are completely unaffected by this change. Intentionally setting a bound value to `undefined` (sic) is jeopardy within Polymer. This behavior is not affected by this PR.

@samccone Sure this will break wildly. The iron-elements people often use the (internally named complex) observer with one dependency instead of the property observer. But from looking at their code it is not even clear they consciously made a decision to opt-in for undefined's. It's more likely they just want to see `null`s or generally falsey values. Maybe they even waste time, doing computations with undefined's.

@MeTaNoV I did not get it down to the spec. Actually just the *first* evaluation of such an computational expression should be delayed until all its dependencies are initialized. But I'm not convinced that this is an actually good idea.

Let me state, that I encountered all three issues/bugs this PR solves in real life. So, this is not a bare hygienic change. **I actually had these issues** using Polymer.

**Comment by mercmobily** [comment]
FWIW, I also encountered _all_ of these problems. Not in real life... But while studying polymer and going through every single sentence in the documentation (with the aim to commit everything to memory).

I am the last kid in the block here and I most certainly don't know the implications for existing code, but I would LOVE to see all of those issued fixed -- if this PR does it and if it's barely acceptable...

**Comment by kaste** [comment]
A puzzle: Write a test that shows how you can get a `undefined` from Polymer in a so-called 'complex' observer with only one dependency. 

- array.splices are out b/c it's a reported bug. 
- Just assigning `undefined` is obviously not allowed as well.

**Comment by kaste** [comment]
By solving my own puzzle I now have a different and actually correct understanding of the problem `dom-repeat` tries to solve. I'll open another PR about undefined's the user wants to handle. Together with my #3439 there will then be 3 PR's around evaluation of complex expressions.

**Comment by kaste** [comment]
The follow-up PR is #3452

**Comment by kaste** [comment]
I'm not convinced anymore that this is a good change. Feel free to close it.

**Comment by TimvdLippe** [comment]
Observers run with `undefined` in Polymer 2 as described in [the upgrade guide](https://www.polymer-project.org/2.0/docs/upgrade#update-observers), therefore I am closing this PR.

**Pull request closed without merging**
