### PR TITLE
selectItems, selectAll, and tests

### LINKED ISSUE #3176: array-selector needs selectAll method
I'm using array-selector with an iron-list and many thousands of items.  I need to implement a `selectAll` method and have found two ways of doing so, neither optimal.  The first is to simply assign to the array-selector's `selected` property.  This is very fast and appears to work at first but bypasses the internal linkages such that nothing can be deselected.  The second technique is this:

```
var s = this.$.selector;
var items = s.items;
for (var i=0; i<items.length; ++i){
    s.select(items[i]);
}
```

This works but is very slow, and in my case causes Chrome to prompt me to kill the page due to unresponsiveness.

If the internals of array-selector allow for it, a `selectAll` would be extremely helpful.

### LINKED ISSUE #3827: array-selector to select all / deselect all
Looking at the documentation it seems we can't do select all / deselect all with array-selector. It would be great if this element can get that feature. Its very common that we have to use select all / deselect all. Anyone knows how we can implement a work-around for this with array-selector ? I tried to at onload to iterate the master array and run the code to select / deselect all but its not working for me. Thanks for your help !

### PR DESCRIPTION
**Pull request by Westbrook**
### Reference Issue
Fixes #3176
Fixes #3827

This relates to the 2.x version of this PR #4699.

These two PRs will allow me to fully address the changes needed for PolymerElements/iron-list#436.

### CODE REVIEW

**Comment by Westbrook** [comment]
Any thoughts on this from the team? I'd be happy to make any changes to the code, comments, tests, or PR that would allow us to move forward with this. It seems like a good amount of people would also be happy for the addition, and it would it would be really helpful in the conversion to 2.0 that my team and I are working on.

**Comment by Westbrook** [comment]
I know that there is very little 1.x work being done, but I did see the recent patch that went out and am seeing the `<custom-style>` work being back ported to there, does anyone have any thoughts as to whether we could get this on the docket for the release that has to come together for that? Possibly @TimvdLippe, who's been making amazing waves on the issues/PR scene?

**Comment by TimvdLippe** [comment]
The `<custom-style>` changes were required to prevent an upcoming Chrome change to break Polymer websites. This PR targets new functionality, so depending if #4699 gets merged, we might merge this one. The reason we have not reviewed the PRs is because we have to quantify the benefit of shipping and maintaing the extra API. E.g. maybe it is possible already with element extension to implement this functionality. Probably this afternoon we can take a look and give you some feedback :smile:

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/pull/4699#issuecomment-331311907 Check out the JSBin over there 😄

**Pull request closed without merging**
