### PR TITLE
Fixes #3676: retain <style> in <template preserve-content/>

### LINKED ISSUE #3676: "preserve-content" attribute does not protect style tags nested in templates
A `<template preserve-content/>` like the following #template:
```
<template preserve-content id="template">
  <div id="retained"></div>
  <style id="lost"></style>
</template>
``` 
will retain the `<div/>` but will lose the `<style/>` when nested inside of the main `<template/>` of a `<dom-module>`.

See http://jsbin.com/fixotaquno/edit?html,output

I think it would be preferable for any `<template preserve-content>` -- perhaps aside from the main `<template/>` of a `<dom-module>` -- to preserve its contents in their entirety.

This functionality seems achievable by adding some conditions around https://github.com/Polymer/polymer/blob/409ad8347b25ab029a72d821c27d9cccdc9f5ac7/src/lib/style-util.html#L145

I will follow with a PR.

### PR DESCRIPTION
**Pull request by jcmoore**
Fixes #3676

- check for `preserve-content` attribute on `<template/>`s in when gathering css

### CODE REVIEW

**Comment by jcmoore** [comment]
Company CLA should already exist for: MediaMath, Inc.

**Comment by jcmoore** [comment]
I signed it!

*Company CLA should already exist for: MediaMath, Inc.*

**Comment by jcmoore** [comment]
I signed it!

**Comment by jcmoore** [comment]
Anyone?  Maybe @kevinpschaaf ?

**Comment by kevinpschaaf** [comment]
LGTM, will review with @sorvell next week.

**Comment by azakus** [comment]
Sorry, I can't find MediaMath, INC, or you individually, in the our list of CLA signers.
Can you double check all the fields are filled out correctly in the Corporate CLA?
Thanks!

**Comment by sorvell** [comment]
LGTM to me too.

**Comment by jcmoore** [comment]
Ok, I've changed the email address on the commit and I've had that email added to the mediamath-google-contributors google group.  @azakus I don't actually see a place to confirm that my organization has already signed the CLA -- as I have been told that they have (around July/August 2015).  Given this new information and recent developments, can someone please let me know if anything additional needs to be done on our end?

**Comment by jcmoore** [comment]
Ah, just now got word that our legal team resigned the CLA (and that it may only have just now been properly associated with the aforementioned google group).

Sorry for the confusion there, hopefully we are good to go!(?)

**Comment by jcmoore** [comment]
Should I just close this PR and open a new one or something?

**Pull request closed without merging**
